apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonsai
spec:
  selector:
    matchLabels:
      app: bonsai
  template:
    metadata:
      labels:
        app: bonsai
    spec:
      containers:
      - name: auth
        image: kadekpradnyana/bonsai-auth-mgmt
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      - name: user
        image: kadekpradnyana/bonsai-user-mgmt
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3010
        - containerPort: 4010

---

apiVersion: v1
kind: Service
metadata:
  name: bonsai
spec:
  type: NodePort
  selector:
    app: bonsai
  ports:
  - port: 3000
    targetPort: 3000
  - port: 3010
    targetPort: 3010
  - port: 4010
    targetPort: 4010

